require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql
AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'  
    - config/**/*
    - db/**/*
    - app/helpers/**/*
    - app/graphql/**/*
    - app/models/application_record.rb
    - bin/**/*
    - lib/audit.rb
    - lib/tasks/**.rake
    - scripts/*
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/ParenthesesAroundCondition:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/Documentation:
  Exclude:
    - app/graphql/**/*
    - test/**/*
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - test/factories/**/*
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 13
Naming/PredicateName:
  Enabled: false
Naming/BlockForwarding:
  EnforcedStyle: explicit
Style/ArgumentsForwarding:
  UseAnonymousForwarding: false
Metrics/ModuleLength:
  Exclude:
    - app/helpers/**/*
Style/RescueModifier:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Rails/EnvironmentVariableAccess:
  AllowReads: true
Style/WordArray:
  EnforcedStyle: brackets
Rails/EagerEvaluationLogMessage:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
