require: rubocop-rails
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/Documentation:
  Exclude:
    - app/graphql/**/*
Metrics/BlockLength:
  Exclude:
    - config/routes.rb
