redisconf: &redisconf
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

production:
  <<: *redisconf
  channel_prefix: hourglass_production

development:
  <<: *redisconf
  channel_prefix: hourglass_development

test:
  adapter: postgresql
