name: ESLint
on:
  pull_request:
    branches: [ master ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install yarn packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
