name: CI
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Install cachix
      uses: cachix/cachix-action@v10
      with:
        name: hourglass
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Get nix deps
      run: nix develop -c echo
    - name: Install ruby gems
      run: nix develop -c bundle install --jobs 4 --retry 3
    - name: Install npm packages
      run: nix develop -c yarn install --frozen-lockfile
    - name: Setup postgres
      run: |
        nix develop -c start_postgres
        nix develop -c rails db:setup
    - name: Write graphql schema file
      run: nix develop -c rails graphql:update_schema
    - name: Compile relay queries
      run: nix develop -c yarn run relay-persist
    - name: Typecheck
      run: nix develop -c yarn run typecheck
    - name: Lint factories
      run: nix develop -c rails factory_bot:lint
    - name: Run tests
      run: nix develop -c rails test
    - name: Lint
      run: nix develop -c yarn run lint
