name: Rails Tests
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .nix-gems/
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: cachix/install-nix-action@v10
    - name: Get nix deps
      run: nix-shell --run 'echo'
    - name: Install ruby gems
      run: nix-shell --run 'bundle install --jobs 4 --retry 3'
    - name: Install npm packages
      run: nix-shell --run 'yarn install --frozen-lockfile'
    - name: Setup postgres
      run: |
        nix-shell --pure --run 'start_postgres'
        nix-shell --pure --run 'rails db:setup'
    - name: Lint factories
      run: nix-shell --pure --run 'rails factory_bot:lint'
    - name: Run tests
      run: nix-shell --pure --run 'rails test'
