name: CI
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Get nix deps
      run: nix-shell --run 'echo'
    - name: Install ruby gems
      run: nix-shell --run 'bundle install --jobs 4 --retry 3'
    - name: Install npm packages
      run: nix-shell --run 'yarn install --frozen-lockfile'
    - name: Setup postgres
      run: |
        nix-shell --run 'start_postgres'
        nix-shell --run 'rails db:setup'
    - name: Write graphql schema file
      run: nix-shell --run 'rails graphql:update_schema'
    - name: Compile relay queries
      run: nix-shell --run 'yarn run relay-persist'
    - name: Typecheck
      run: nix-shell --run 'yarn run typecheck'
    - name: Lint factories
      run: nix-shell --run 'rails factory_bot:lint'
    - name: Run tests
      run: nix-shell --run 'rails test'
    - name: Lint
      run: nix-shell --run 'yarn run lint'
