name: Typecheck
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install yarn packages
        run: yarn install --frozen-lockfile
      - name: Compile relay queries
        run: yarn run relay
      - name: Typecheck
        run: yarn typecheck
